// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: qlight-token-manager.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PluginQLightTokenManager struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PluginQLightTokenManager) Reset() {
	*x = PluginQLightTokenManager{}
	if protoimpl.UnsafeEnabled {
		mi := &file_qlight_token_manager_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PluginQLightTokenManager) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginQLightTokenManager) ProtoMessage() {}

func (x *PluginQLightTokenManager) ProtoReflect() protoreflect.Message {
	mi := &file_qlight_token_manager_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginQLightTokenManager.ProtoReflect.Descriptor instead.
func (*PluginQLightTokenManager) Descriptor() ([]byte, []int) {
	return file_qlight_token_manager_proto_rawDescGZIP(), []int{0}
}

type PluginQLightTokenManager_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CurrentToken string `protobuf:"bytes,1,opt,name=currentToken,proto3" json:"currentToken,omitempty"`
}

func (x *PluginQLightTokenManager_Request) Reset() {
	*x = PluginQLightTokenManager_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_qlight_token_manager_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PluginQLightTokenManager_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginQLightTokenManager_Request) ProtoMessage() {}

func (x *PluginQLightTokenManager_Request) ProtoReflect() protoreflect.Message {
	mi := &file_qlight_token_manager_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginQLightTokenManager_Request.ProtoReflect.Descriptor instead.
func (*PluginQLightTokenManager_Request) Descriptor() ([]byte, []int) {
	return file_qlight_token_manager_proto_rawDescGZIP(), []int{0, 0}
}

func (x *PluginQLightTokenManager_Request) GetCurrentToken() string {
	if x != nil {
		return x.CurrentToken
	}
	return ""
}

type PluginQLightTokenManager_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *PluginQLightTokenManager_Response) Reset() {
	*x = PluginQLightTokenManager_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_qlight_token_manager_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PluginQLightTokenManager_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginQLightTokenManager_Response) ProtoMessage() {}

func (x *PluginQLightTokenManager_Response) ProtoReflect() protoreflect.Message {
	mi := &file_qlight_token_manager_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginQLightTokenManager_Response.ProtoReflect.Descriptor instead.
func (*PluginQLightTokenManager_Response) Descriptor() ([]byte, []int) {
	return file_qlight_token_manager_proto_rawDescGZIP(), []int{0, 1}
}

func (x *PluginQLightTokenManager_Response) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

var File_qlight_token_manager_proto protoreflect.FileDescriptor

var file_qlight_token_manager_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x71, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x2d, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x2d, 0x6d,
	0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x6b, 0x0a, 0x18, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x51, 0x4c, 0x69,
	0x67, 0x68, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x1a,
	0x2d, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x22, 0x0a, 0x0c, 0x63, 0x75,
	0x72, 0x72, 0x65, 0x6e, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0c, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x1a, 0x20,
	0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f,
	0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x32, 0x7f, 0x0a, 0x1a, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x51, 0x4c, 0x69, 0x67, 0x68, 0x74,
	0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x65, 0x72, 0x12, 0x61,
	0x0a, 0x0c, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x12, 0x27,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x51, 0x4c, 0x69,
	0x67, 0x68, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x28, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x51, 0x4c, 0x69, 0x67, 0x68, 0x74, 0x54, 0x6f, 0x6b, 0x65,
	0x6e, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x42, 0x36, 0x0a, 0x17, 0x63, 0x6f, 0x6d, 0x2e, 0x71, 0x75, 0x6f, 0x72, 0x75, 0x6d, 0x2e,
	0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x42, 0x12, 0x51, 0x4c,
	0x69, 0x67, 0x68, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72,
	0x5a, 0x07, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_qlight_token_manager_proto_rawDescOnce sync.Once
	file_qlight_token_manager_proto_rawDescData = file_qlight_token_manager_proto_rawDesc
)

func file_qlight_token_manager_proto_rawDescGZIP() []byte {
	file_qlight_token_manager_proto_rawDescOnce.Do(func() {
		file_qlight_token_manager_proto_rawDescData = protoimpl.X.CompressGZIP(file_qlight_token_manager_proto_rawDescData)
	})
	return file_qlight_token_manager_proto_rawDescData
}

var file_qlight_token_manager_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_qlight_token_manager_proto_goTypes = []interface{}{
	(*PluginQLightTokenManager)(nil),          // 0: proto.PluginQLightTokenManager
	(*PluginQLightTokenManager_Request)(nil),  // 1: proto.PluginQLightTokenManager.Request
	(*PluginQLightTokenManager_Response)(nil), // 2: proto.PluginQLightTokenManager.Response
}
var file_qlight_token_manager_proto_depIdxs = []int32{
	1, // 0: proto.PluginQLightTokenRefresher.TokenRefresh:input_type -> proto.PluginQLightTokenManager.Request
	2, // 1: proto.PluginQLightTokenRefresher.TokenRefresh:output_type -> proto.PluginQLightTokenManager.Response
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_qlight_token_manager_proto_init() }
func file_qlight_token_manager_proto_init() {
	if File_qlight_token_manager_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_qlight_token_manager_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PluginQLightTokenManager); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_qlight_token_manager_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PluginQLightTokenManager_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_qlight_token_manager_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PluginQLightTokenManager_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_qlight_token_manager_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_qlight_token_manager_proto_goTypes,
		DependencyIndexes: file_qlight_token_manager_proto_depIdxs,
		MessageInfos:      file_qlight_token_manager_proto_msgTypes,
	}.Build()
	File_qlight_token_manager_proto = out.File
	file_qlight_token_manager_proto_rawDesc = nil
	file_qlight_token_manager_proto_goTypes = nil
	file_qlight_token_manager_proto_depIdxs = nil
}
